[versions]
rei = "6.0.264-alpha"

[libraries]
# Common Deps
jetbrainAnnotations = { group = "org.jetbrains", name = "annotations", version = "21.0.1" }
# Forge Deps
minecraft-forge = { group = "net.minecraftforge", name = "forge", version = "1.17.1-37.0.19" }
jei-api = { group = "local", name = "jei-1.17.1", version = "5b4ef8b2ce7bb01ef5ee8d699bdb4da6cd8d8b42:api" }
# Fabric Deps
minecraft-fabric = { group = "com.mojang", name = "minecraft", version = "1.17.1" }
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version = "0.11.3" }
fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version = "0.38.0+1.17" }
rei = { group = "me.shedaniel", name = "RoughlyEnoughItems-fabric", version.ref = "rei" }
rei-api = { group = "me.shedaniel", name = "RoughlyEnoughItems-api-fabric", version.ref = "rei" }
modmenu = { group = "com.terraformersmc", name = "modmenu", version = "2.0.0-beta.7" }
amecs-api = { group = "de.siphalor", name = "amecsapi-1.17", version = "1.1.+" }
statement = { group = "com.github.Virtuoel", name = "Statement", version = "31a2c3f" }
towelette = { group = "com.github.Virtuoel", name = "Towelette", version = "e5e39eb" }
heyThatsMine = { group = "local", name = "htm", version = "dda0f76870e3a424af53416603ff489b1c733b3d" }

[plugins]
# Common Plugins
gradleUtils = { id = "com.gitlab.ninjaphenix.gradle-utils", version = "0.1.0-beta.4" }
# Forge Plugins
forgeGradle = { id = "net.minecraftforge.gradle", version = "5.1.18" }
# Fabric Plugins
fabricLoom = { id = "fabric-loom", version = "0.9.45" }
