[versions]
rei = "6.0.264-alpha"
containerlib = "1.0.0+1.17.1"

[libraries]
# Common Deps
jetbrainAnnotations = { group = "org.jetbrains", name = "annotations", version = "22.0.0" }
# Forge Deps
minecraft-forge = { group = "net.minecraftforge", name = "forge", version = "1.17.1-37.0.19" }
containerLibrary-forge = { group = "ninjaphenix.container_library", name = "forge", version.ref = "containerlib" }
containerLibrary-forge-runtime = { group = "local", name = "ninjaphenix-container-library", version = "1.0.0+1.17.1-named" }
# Fabric Deps
minecraft-fabric = { group = "com.mojang", name = "minecraft", version = "1.17.1" }
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version = "0.11.3" }
fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version = "0.39.1+1.17" }
statement = { group = "com.github.Virtuoel", name = "Statement", version = "31a2c3f" }
towelette = { group = "com.github.Virtuoel", name = "Towelette", version = "e5e39eb" }
heyThatsMine = { group = "local", name = "htm", version = "dda0f76870e3a424af53416603ff489b1c733b3d" }
containerLibrary-fabric = { group = "ninjaphenix.container_library", name = "fabric", version.ref = "containerlib" }

[plugins]
# Common Plugins
gradleUtils = { id = "com.gitlab.ninjaphenix.gradle-utils", version = "0.1.0-beta.5" }
# Forge Plugins
forgeGradle = { id = "ninjaphenix.minecraftforge.gradle", version = "5.1.23" }
# Fabric Plugins
fabricLoom = { id = "ninja-loom", version = "0.10.local" }
